apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-dep
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
        - name: postgres-container
          image: postgres
          env:
            - name: POSTGRES_DB
              value: cartdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          ports:
            - containerPort: 3020
        - name: challenge-container
          image: deboraferrarids2/challenge_web:v2.0
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-key
            - name: DATABASE_HOST
              value: db
          ports:
            - containerPort: 6060
